import type { Resource } from "@/lib/domain/types";

// ── Curated resource catalog ──────────────────────────────────────────────────
// Real, well-known resources with plausible metadata. Every skill referenced by
// a role is taught by at least one resource here. URLs open externally.

export const RESOURCES: Resource[] = [
  // ── Foundations ────────────────────────────────────────────────────────────
  { id: "r-py4e", title: "Python for Everybody", type: "course", domain: "Programming", difficulty: "beginner", skills: ["python", "programming-fundamentals"], prerequisites: [], durationHours: 20, description: "A gentle, project-based introduction to programming with Python.", url: "https://www.py4e.com/", tags: ["python", "beginner", "video"], provider: "Coursera / freeCodeCamp" },
  { id: "r-cs50", title: "CS50x: Introduction to Computer Science", type: "course", domain: "Programming", difficulty: "beginner", skills: ["programming-fundamentals"], prerequisites: [], durationHours: 40, description: "Harvard's rigorous intro to computer science and problem solving.", url: "https://cs50.harvard.edu/x/", tags: ["fundamentals", "cs"], provider: "Harvard / edX" },
  { id: "r-python-docs", title: "The Python Tutorial (Official Docs)", type: "documentation", domain: "Programming", difficulty: "beginner", skills: ["python"], prerequisites: [], durationHours: 6, description: "Authoritative reference-style walkthrough of the language.", url: "https://docs.python.org/3/tutorial/", tags: ["reference", "python"], provider: "python.org" },
  { id: "r-git", title: "Learn Git Branching", type: "tutorial", domain: "Software", difficulty: "beginner", skills: ["git"], prerequisites: [], durationHours: 4, description: "Interactive, visual way to master Git branching.", url: "https://learngitbranching.js.org/", tags: ["git", "interactive"], provider: "learngitbranching" },
  { id: "r-linux", title: "The Linux Command Line", type: "book", domain: "Software", difficulty: "beginner", skills: ["linux-cli"], prerequisites: [], durationHours: 12, description: "A complete introduction to the shell and Linux systems.", url: "https://linuxcommand.org/tlcl.php", tags: ["linux", "cli", "book"], provider: "William Shotts" },

  // ── Math ────────────────────────────────────────────────────────────────────
  { id: "r-linalg", title: "Essence of Linear Algebra", type: "tutorial", domain: "Math", difficulty: "beginner", skills: ["math-linear-algebra"], prerequisites: [], durationHours: 5, description: "Visual, intuition-first linear algebra from 3Blue1Brown.", url: "https://www.3blue1brown.com/topics/linear-algebra", tags: ["math", "visual", "video"], provider: "3Blue1Brown" },
  { id: "r-stats", title: "Statistics & Probability", type: "course", domain: "Math", difficulty: "beginner", skills: ["statistics"], prerequisites: [], durationHours: 15, description: "Descriptive and inferential statistics, hands-on.", url: "https://www.khanacademy.org/math/statistics-probability", tags: ["statistics", "math"], provider: "Khan Academy" },
  { id: "r-prob", title: "Introduction to Probability", type: "course", domain: "Math", difficulty: "intermediate", skills: ["probability"], prerequisites: ["statistics"], durationHours: 12, description: "Distributions, expectation, and probabilistic reasoning.", url: "https://www.edx.org/learn/probability", tags: ["probability", "math"], provider: "edX" },

  // ── Data ────────────────────────────────────────────────────────────────────
  { id: "r-sql", title: "The SQL Tutorial for Data Analysis", type: "tutorial", domain: "Data", difficulty: "beginner", skills: ["sql"], prerequisites: [], durationHours: 8, description: "Practical SQL for slicing real datasets.", url: "https://mode.com/sql-tutorial/", tags: ["sql", "data"], provider: "Mode" },
  { id: "r-pandas", title: "Pandas", type: "course", domain: "Data", difficulty: "beginner", skills: ["data-wrangling"], prerequisites: ["python"], durationHours: 6, description: "Hands-on dataframe manipulation on Kaggle.", url: "https://www.kaggle.com/learn/pandas", tags: ["pandas", "data"], provider: "Kaggle Learn" },
  { id: "r-numpy", title: "NumPy: the absolute basics", type: "documentation", domain: "Data", difficulty: "beginner", skills: ["data-wrangling"], prerequisites: ["python"], durationHours: 3, description: "Array programming foundations for scientific Python.", url: "https://numpy.org/doc/stable/user/absolute_beginners.html", tags: ["numpy", "reference"], provider: "numpy.org" },
  { id: "r-dataviz", title: "Data Visualization", type: "course", domain: "Data", difficulty: "beginner", skills: ["data-visualization"], prerequisites: ["data-wrangling"], durationHours: 5, description: "Build clear, honest charts that communicate.", url: "https://www.kaggle.com/learn/data-visualization", tags: ["viz", "matplotlib"], provider: "Kaggle Learn" },
  { id: "r-cleaning", title: "Data Cleaning", type: "course", domain: "Data", difficulty: "beginner", skills: ["data-cleaning"], prerequisites: ["data-wrangling"], durationHours: 4, description: "Handle missing values, scaling, dates, and messy text.", url: "https://www.kaggle.com/learn/data-cleaning", tags: ["cleaning", "data"], provider: "Kaggle Learn" },
  { id: "r-eda-project", title: "Project: Exploratory Data Analysis", type: "project", domain: "Data", difficulty: "intermediate", skills: ["eda"], prerequisites: ["data-wrangling", "data-visualization", "statistics"], durationHours: 8, description: "Profile a real dataset end-to-end and present findings.", url: "https://www.kaggle.com/datasets", tags: ["eda", "project", "portfolio"], provider: "Kaggle" },

  // ── Machine Learning ─────────────────────────────────────────────────────────
  { id: "r-ml-spec", title: "Machine Learning Specialization", type: "course", domain: "Machine Learning", difficulty: "intermediate", skills: ["ml-fundamentals", "supervised-learning"], prerequisites: ["python", "statistics", "math-linear-algebra"], durationHours: 30, description: "Andrew Ng's modern ML foundations.", url: "https://www.coursera.org/specializations/machine-learning-introduction", tags: ["ml", "andrew-ng"], provider: "DeepLearning.AI" },
  { id: "r-ml-intro", title: "Intro to Machine Learning", type: "course", domain: "Machine Learning", difficulty: "beginner", skills: ["ml-fundamentals"], prerequisites: ["data-wrangling"], durationHours: 5, description: "Train your first models quickly with scikit-learn.", url: "https://www.kaggle.com/learn/intro-to-machine-learning", tags: ["ml", "sklearn"], provider: "Kaggle Learn" },
  { id: "r-sklearn", title: "scikit-learn: Supervised Learning", type: "documentation", domain: "Machine Learning", difficulty: "intermediate", skills: ["supervised-learning"], prerequisites: ["ml-fundamentals"], durationHours: 8, description: "The reference for classification and regression in Python.", url: "https://scikit-learn.org/stable/supervised_learning.html", tags: ["sklearn", "reference"], provider: "scikit-learn" },
  { id: "r-unsup", title: "Clustering & Dimensionality Reduction", type: "tutorial", domain: "Machine Learning", difficulty: "intermediate", skills: ["unsupervised-learning"], prerequisites: ["ml-fundamentals"], durationHours: 6, description: "k-means, hierarchical clustering, and PCA in practice.", url: "https://scikit-learn.org/stable/unsupervised_learning.html", tags: ["clustering", "pca"], provider: "scikit-learn" },
  { id: "r-modeleval", title: "Model Evaluation & Validation", type: "tutorial", domain: "Machine Learning", difficulty: "intermediate", skills: ["model-evaluation"], prerequisites: ["supervised-learning"], durationHours: 6, description: "Cross-validation, metrics, and avoiding data leakage.", url: "https://scikit-learn.org/stable/modules/model_evaluation.html", tags: ["metrics", "validation"], provider: "scikit-learn" },
  { id: "r-featureeng", title: "Feature Engineering", type: "course", domain: "Machine Learning", difficulty: "intermediate", skills: ["feature-engineering"], prerequisites: ["data-wrangling", "ml-fundamentals"], durationHours: 5, description: "Craft features that make models measurably better.", url: "https://www.kaggle.com/learn/feature-engineering", tags: ["features", "ml"], provider: "Kaggle Learn" },
  { id: "r-fastai", title: "Practical Deep Learning for Coders", type: "course", domain: "Machine Learning", difficulty: "intermediate", skills: ["deep-learning"], prerequisites: ["supervised-learning"], durationHours: 24, description: "Top-down deep learning you can apply immediately.", url: "https://course.fast.ai/", tags: ["deep-learning", "pytorch"], provider: "fast.ai" },
  { id: "r-dl-spec", title: "Deep Learning Specialization", type: "course", domain: "Machine Learning", difficulty: "advanced", skills: ["deep-learning"], prerequisites: ["supervised-learning", "math-linear-algebra"], durationHours: 35, description: "Neural nets from the ground up.", url: "https://www.coursera.org/specializations/deep-learning", tags: ["deep-learning", "andrew-ng"], provider: "DeepLearning.AI" },
  { id: "r-hf-nlp", title: "Hugging Face NLP Course", type: "course", domain: "Machine Learning", difficulty: "advanced", skills: ["nlp"], prerequisites: ["deep-learning"], durationHours: 18, description: "Transformers and modern NLP, hands-on.", url: "https://huggingface.co/learn/nlp-course", tags: ["nlp", "transformers"], provider: "Hugging Face" },
  { id: "r-cv", title: "Computer Vision Fundamentals", type: "tutorial", domain: "Machine Learning", difficulty: "advanced", skills: ["computer-vision"], prerequisites: ["deep-learning"], durationHours: 10, description: "CNNs and image tasks with PyTorch.", url: "https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html", tags: ["cv", "pytorch"], provider: "PyTorch" },

  // ── Software / MLOps ─────────────────────────────────────────────────────────
  { id: "r-fastapi", title: "Build APIs with FastAPI", type: "tutorial", domain: "Software", difficulty: "intermediate", skills: ["software-apis"], prerequisites: ["python"], durationHours: 8, description: "Design and ship typed HTTP APIs in Python.", url: "https://fastapi.tiangolo.com/tutorial/", tags: ["api", "fastapi"], provider: "FastAPI" },
  { id: "r-deploy", title: "Project: Deploy an ML Model as an API", type: "project", domain: "MLOps", difficulty: "intermediate", skills: ["model-deployment"], prerequisites: ["ml-fundamentals", "software-apis"], durationHours: 10, description: "Wrap a trained model in FastAPI and containerize it.", url: "https://fastapi.tiangolo.com/deployment/", tags: ["deployment", "project"], provider: "FastAPI" },
  { id: "r-pipelines", title: "Building ML Pipelines", type: "tutorial", domain: "MLOps", difficulty: "advanced", skills: ["ml-pipelines"], prerequisites: ["model-deployment"], durationHours: 8, description: "Automate data + training workflows reproducibly.", url: "https://scikit-learn.org/stable/modules/compose.html", tags: ["pipelines", "mlops"], provider: "scikit-learn" },
  { id: "r-mlops", title: "MLOps (Made With ML)", type: "course", domain: "MLOps", difficulty: "advanced", skills: ["mlops"], prerequisites: ["model-deployment", "docker"], durationHours: 20, description: "Design, develop, deploy, and iterate on production ML.", url: "https://madewithml.com/", tags: ["mlops", "production"], provider: "Made With ML" },
  { id: "r-monitor", title: "Monitoring ML in Production", type: "tutorial", domain: "MLOps", difficulty: "advanced", skills: ["model-monitoring"], prerequisites: ["mlops"], durationHours: 6, description: "Detect drift, decay, and data quality issues.", url: "https://www.evidentlyai.com/ml-in-production", tags: ["monitoring", "drift"], provider: "Evidently AI" },
  { id: "r-db", title: "Databases & SQL Deep Dive", type: "course", domain: "Software", difficulty: "intermediate", skills: ["databases"], prerequisites: ["sql"], durationHours: 12, description: "Relational modeling, indexing, and transactions.", url: "https://www.postgresql.org/docs/current/tutorial.html", tags: ["databases", "postgres"], provider: "PostgreSQL" },
  { id: "r-pytest", title: "Python Testing with pytest", type: "tutorial", domain: "Software", difficulty: "intermediate", skills: ["testing"], prerequisites: ["python"], durationHours: 6, description: "Write fast, reliable automated tests.", url: "https://docs.pytest.org/", tags: ["testing", "pytest"], provider: "pytest" },
  { id: "r-sysdesign", title: "The System Design Primer", type: "documentation", domain: "Software", difficulty: "advanced", skills: ["system-design"], prerequisites: ["software-apis", "databases"], durationHours: 14, description: "Learn to design scalable systems (with examples).", url: "https://github.com/donnemartin/system-design-primer", tags: ["system-design", "scalability"], provider: "GitHub" },

  // ── Cloud / DevOps ──────────────────────────────────────────────────────────
  { id: "r-docker", title: "Docker: Getting Started", type: "tutorial", domain: "Cloud", difficulty: "beginner", skills: ["docker"], prerequisites: ["linux-cli"], durationHours: 5, description: "Package and run apps in containers.", url: "https://docs.docker.com/get-started/", tags: ["docker", "containers"], provider: "Docker" },
  { id: "r-cicd", title: "CI/CD with GitHub Actions", type: "tutorial", domain: "Cloud", difficulty: "intermediate", skills: ["ci-cd"], prerequisites: ["git", "docker"], durationHours: 6, description: "Automate build, test, and deploy pipelines.", url: "https://docs.github.com/en/actions/learn-github-actions", tags: ["ci-cd", "github-actions"], provider: "GitHub" },
  { id: "r-cloud", title: "AWS Cloud Practitioner Essentials", type: "course", domain: "Cloud", difficulty: "beginner", skills: ["cloud-fundamentals"], prerequisites: [], durationHours: 10, description: "Core cloud concepts and the AWS mental model.", url: "https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/", tags: ["aws", "cloud"], provider: "AWS" },
  { id: "r-compute", title: "Cloud Compute: VMs & Serverless", type: "tutorial", domain: "Cloud", difficulty: "intermediate", skills: ["cloud-compute"], prerequisites: ["cloud-fundamentals"], durationHours: 6, description: "Run workloads on VMs, containers, and functions.", url: "https://aws.amazon.com/getting-started/hands-on/", tags: ["compute", "serverless"], provider: "AWS" },
  { id: "r-storage", title: "Cloud Storage & Managed Databases", type: "tutorial", domain: "Cloud", difficulty: "intermediate", skills: ["cloud-storage"], prerequisites: ["cloud-fundamentals"], durationHours: 5, description: "Object stores, managed DBs, and caching layers.", url: "https://aws.amazon.com/getting-started/hands-on/", tags: ["storage", "s3"], provider: "AWS" },
  { id: "r-iac", title: "Terraform: Get Started", type: "tutorial", domain: "Cloud", difficulty: "intermediate", skills: ["infrastructure-as-code"], prerequisites: ["cloud-fundamentals"], durationHours: 8, description: "Provision cloud infra declaratively.", url: "https://developer.hashicorp.com/terraform/tutorials", tags: ["terraform", "iac"], provider: "HashiCorp" },
  { id: "r-k8s", title: "Kubernetes Basics", type: "tutorial", domain: "Cloud", difficulty: "advanced", skills: ["kubernetes"], prerequisites: ["docker", "cloud-compute"], durationHours: 10, description: "Deploy and scale containers with Kubernetes.", url: "https://kubernetes.io/docs/tutorials/kubernetes-basics/", tags: ["kubernetes", "orchestration"], provider: "Kubernetes" },

  // ── AI & LLMs ────────────────────────────────────────────────────────────────
  { id: "r-genai-everyone", title: "Generative AI for Everyone", type: "course", domain: "AI & LLMs", difficulty: "beginner", skills: ["llm-fundamentals"], prerequisites: [], durationHours: 6, description: "How generative AI works and where it fits.", url: "https://www.coursera.org/learn/generative-ai-for-everyone", tags: ["genai", "intro"], provider: "DeepLearning.AI" },
  { id: "r-llm-fund", title: "How LLMs Work + Building with APIs", type: "tutorial", domain: "AI & LLMs", difficulty: "intermediate", skills: ["llm-fundamentals"], prerequisites: ["python"], durationHours: 6, description: "Tokens, context windows, sampling, and calling model APIs.", url: "https://platform.openai.com/docs/guides/text-generation", tags: ["llm", "api"], provider: "OpenAI Docs" },
  { id: "r-prompt", title: "ChatGPT Prompt Engineering for Developers", type: "course", domain: "AI & LLMs", difficulty: "beginner", skills: ["prompt-engineering"], prerequisites: ["llm-fundamentals"], durationHours: 4, description: "Systematic prompting, iteration, and structured outputs.", url: "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/", tags: ["prompting", "llm"], provider: "DeepLearning.AI" },
  { id: "r-embeddings", title: "Embeddings & Semantic Search", type: "tutorial", domain: "AI & LLMs", difficulty: "intermediate", skills: ["embeddings"], prerequisites: ["llm-fundamentals"], durationHours: 5, description: "Represent meaning as vectors and search by similarity.", url: "https://www.pinecone.io/learn/vector-embeddings/", tags: ["embeddings", "search"], provider: "Pinecone" },
  { id: "r-vectordb", title: "Vector Databases", type: "tutorial", domain: "AI & LLMs", difficulty: "intermediate", skills: ["vector-databases"], prerequisites: ["embeddings"], durationHours: 5, description: "Index and query embeddings at scale.", url: "https://www.pinecone.io/learn/vector-database/", tags: ["vectordb", "retrieval"], provider: "Pinecone" },
  { id: "r-rag", title: "Project: Build a RAG Application", type: "project", domain: "AI & LLMs", difficulty: "advanced", skills: ["rag"], prerequisites: ["prompt-engineering", "embeddings"], durationHours: 12, description: "Ground an LLM in your own documents end-to-end.", url: "https://python.langchain.com/docs/tutorials/rag/", tags: ["rag", "project"], provider: "LangChain" },
  { id: "r-llmapps", title: "Building LLM-Powered Applications", type: "course", domain: "AI & LLMs", difficulty: "intermediate", skills: ["llm-apps"], prerequisites: ["prompt-engineering", "software-apis"], durationHours: 10, description: "Architect reliable apps around LLM APIs.", url: "https://python.langchain.com/docs/tutorials/", tags: ["llm-apps", "langchain"], provider: "LangChain" },
  { id: "r-llmeval", title: "Evaluating LLM Applications", type: "tutorial", domain: "AI & LLMs", difficulty: "advanced", skills: ["llm-evaluation"], prerequisites: ["llm-apps"], durationHours: 5, description: "Build evals so quality doesn't regress.", url: "https://huggingface.co/learn/cookbook/en/llm_judge", tags: ["evals", "quality"], provider: "Hugging Face" },
  { id: "r-agents", title: "Project: Build an AI Agent", type: "project", domain: "AI & LLMs", difficulty: "advanced", skills: ["agents"], prerequisites: ["llm-apps", "rag"], durationHours: 12, description: "A tool-using, multi-step agent with guardrails.", url: "https://python.langchain.com/docs/tutorials/agents/", tags: ["agents", "project"], provider: "LangChain" },
  { id: "r-finetune", title: "Fine-Tuning LLMs", type: "tutorial", domain: "AI & LLMs", difficulty: "advanced", skills: ["fine-tuning"], prerequisites: ["deep-learning", "llm-fundamentals"], durationHours: 8, description: "Adapt open models to your domain.", url: "https://huggingface.co/learn/nlp-course/chapter3/1", tags: ["fine-tuning", "peft"], provider: "Hugging Face" },

  // ── Security ─────────────────────────────────────────────────────────────────
  { id: "r-secfund", title: "Cybersecurity Fundamentals", type: "course", domain: "Security", difficulty: "beginner", skills: ["security-fundamentals"], prerequisites: [], durationHours: 10, description: "Threats, the CIA triad, and defense in depth.", url: "https://www.cybrary.it/course/introduction-to-it-and-cybersecurity/", tags: ["security", "intro"], provider: "Cybrary" },
  { id: "r-networking", title: "Computer Networking", type: "course", domain: "Security", difficulty: "intermediate", skills: ["networking"], prerequisites: [], durationHours: 14, description: "TCP/IP, DNS, routing — the fabric attacks travel on.", url: "https://www.coursera.org/learn/computer-networking", tags: ["networking", "tcp-ip"], provider: "Google / Coursera" },
  { id: "r-crypto", title: "Cryptography I", type: "course", domain: "Security", difficulty: "advanced", skills: ["cryptography"], prerequisites: ["security-fundamentals"], durationHours: 16, description: "Hashing, symmetric/asymmetric crypto, and TLS.", url: "https://www.coursera.org/learn/crypto", tags: ["crypto", "tls"], provider: "Stanford" },
  { id: "r-websec", title: "Web Security Academy", type: "tutorial", domain: "Security", difficulty: "intermediate", skills: ["web-security"], prerequisites: ["security-fundamentals", "software-apis"], durationHours: 12, description: "Hands-on OWASP Top 10 labs.", url: "https://portswigger.net/web-security", tags: ["owasp", "web"], provider: "PortSwigger" },
  { id: "r-threat", title: "Threat Modeling & Analysis", type: "tutorial", domain: "Security", difficulty: "advanced", skills: ["threat-analysis"], prerequisites: ["security-fundamentals", "networking"], durationHours: 6, description: "Identify and prioritize what could go wrong.", url: "https://owasp.org/www-community/Threat_Modeling", tags: ["threat-modeling"], provider: "OWASP" },
  { id: "r-ir", title: "Incident Response Essentials", type: "tutorial", domain: "Security", difficulty: "advanced", skills: ["incident-response"], prerequisites: ["threat-analysis"], durationHours: 6, description: "Detect, contain, eradicate, and recover.", url: "https://www.sans.org/white-papers/", tags: ["incident-response", "blue-team"], provider: "SANS" },
  { id: "r-pentest", title: "Hands-on Penetration Testing", type: "project", domain: "Security", difficulty: "advanced", skills: ["pen-testing"], prerequisites: ["web-security", "networking"], durationHours: 15, description: "Authorized offensive practice on TryHackMe rooms.", url: "https://tryhackme.com/", tags: ["pentest", "labs"], provider: "TryHackMe" },
];

export const RESOURCE_BY_ID: Record<string, Resource> = Object.fromEntries(
  RESOURCES.map((r) => [r.id, r]),
);
