import type { Role } from "@/lib/domain/types";

// ── Target roles ──────────────────────────────────────────────────────────────
// targetLevel: 1 aware · 2 working · 3 strong. `aliases` power fuzzy goal→role
// matching in the fallback extractor.

export const ROLES: Role[] = [
  {
    id: "data-scientist",
    name: "Data Scientist",
    domain: "Data",
    blurb: "Turns data into models and insight that drive decisions.",
    aliases: ["data science", "ds", "data scientist", "analytics scientist"],
    targetSkills: [
      { skillId: "python", targetLevel: 3 },
      { skillId: "sql", targetLevel: 2 },
      { skillId: "statistics", targetLevel: 3 },
      { skillId: "probability", targetLevel: 2 },
      { skillId: "data-wrangling", targetLevel: 3 },
      { skillId: "data-visualization", targetLevel: 2 },
      { skillId: "eda", targetLevel: 3 },
      { skillId: "ml-fundamentals", targetLevel: 3 },
      { skillId: "supervised-learning", targetLevel: 3 },
      { skillId: "unsupervised-learning", targetLevel: 2 },
      { skillId: "model-evaluation", targetLevel: 3 },
      { skillId: "feature-engineering", targetLevel: 2 },
    ],
  },
  {
    id: "ml-engineer",
    name: "Machine Learning Engineer",
    domain: "Machine Learning",
    blurb: "Builds, ships, and operates ML systems in production.",
    aliases: ["ml engineer", "machine learning engineer", "mle", "ml eng"],
    targetSkills: [
      { skillId: "python", targetLevel: 3 },
      { skillId: "data-wrangling", targetLevel: 3 },
      { skillId: "statistics", targetLevel: 2 },
      { skillId: "ml-fundamentals", targetLevel: 3 },
      { skillId: "supervised-learning", targetLevel: 3 },
      { skillId: "model-evaluation", targetLevel: 3 },
      { skillId: "feature-engineering", targetLevel: 3 },
      { skillId: "deep-learning", targetLevel: 2 },
      { skillId: "software-apis", targetLevel: 2 },
      { skillId: "model-deployment", targetLevel: 3 },
      { skillId: "ml-pipelines", targetLevel: 2 },
      { skillId: "docker", targetLevel: 2 },
      { skillId: "mlops", targetLevel: 2 },
    ],
  },
  {
    id: "ai-llm-engineer",
    name: "AI / LLM Engineer",
    domain: "AI & LLMs",
    blurb: "Builds applications and agents on top of large language models.",
    aliases: ["ai engineer", "llm engineer", "genai engineer", "generative ai engineer", "ai/llm engineer", "gen ai"],
    targetSkills: [
      { skillId: "python", targetLevel: 2 },
      { skillId: "software-apis", targetLevel: 3 },
      { skillId: "llm-fundamentals", targetLevel: 3 },
      { skillId: "prompt-engineering", targetLevel: 3 },
      { skillId: "embeddings", targetLevel: 2 },
      { skillId: "vector-databases", targetLevel: 2 },
      { skillId: "rag", targetLevel: 3 },
      { skillId: "llm-apps", targetLevel: 3 },
      { skillId: "llm-evaluation", targetLevel: 2 },
      { skillId: "agents", targetLevel: 2 },
      { skillId: "docker", targetLevel: 2 },
    ],
  },
  {
    id: "backend-engineer",
    name: "Backend Software Engineer",
    domain: "Software",
    blurb: "Designs and builds reliable server-side systems and APIs.",
    aliases: ["backend developer", "backend engineer", "software engineer", "backend", "server developer"],
    targetSkills: [
      { skillId: "programming-fundamentals", targetLevel: 3 },
      { skillId: "python", targetLevel: 2 },
      { skillId: "git", targetLevel: 2 },
      { skillId: "sql", targetLevel: 3 },
      { skillId: "databases", targetLevel: 3 },
      { skillId: "software-apis", targetLevel: 3 },
      { skillId: "testing", targetLevel: 2 },
      { skillId: "system-design", targetLevel: 2 },
      { skillId: "docker", targetLevel: 2 },
      { skillId: "ci-cd", targetLevel: 2 },
    ],
  },
  {
    id: "cloud-engineer",
    name: "Cloud Engineer",
    domain: "Cloud",
    blurb: "Runs scalable, automated infrastructure in the cloud.",
    aliases: ["cloud engineer", "devops engineer", "platform engineer", "sre", "cloud"],
    targetSkills: [
      { skillId: "linux-cli", targetLevel: 3 },
      { skillId: "git", targetLevel: 2 },
      { skillId: "networking", targetLevel: 2 },
      { skillId: "cloud-fundamentals", targetLevel: 3 },
      { skillId: "cloud-compute", targetLevel: 3 },
      { skillId: "cloud-storage", targetLevel: 2 },
      { skillId: "docker", targetLevel: 3 },
      { skillId: "infrastructure-as-code", targetLevel: 2 },
      { skillId: "ci-cd", targetLevel: 2 },
      { skillId: "kubernetes", targetLevel: 2 },
    ],
  },
  {
    id: "data-analyst",
    name: "Data Analyst",
    domain: "Data",
    blurb: "Answers business questions with data and clear visuals.",
    aliases: ["data analyst", "business analyst", "analytics", "bi analyst"],
    targetSkills: [
      { skillId: "sql", targetLevel: 3 },
      { skillId: "statistics", targetLevel: 2 },
      { skillId: "python", targetLevel: 2 },
      { skillId: "data-wrangling", targetLevel: 2 },
      { skillId: "data-cleaning", targetLevel: 2 },
      { skillId: "data-visualization", targetLevel: 3 },
      { skillId: "eda", targetLevel: 2 },
    ],
  },
  {
    id: "security-analyst",
    name: "Cybersecurity Analyst",
    domain: "Security",
    blurb: "Defends systems by detecting, analyzing, and responding to threats.",
    aliases: ["security analyst", "cybersecurity analyst", "soc analyst", "cyber security", "infosec"],
    targetSkills: [
      { skillId: "linux-cli", targetLevel: 2 },
      { skillId: "networking", targetLevel: 3 },
      { skillId: "security-fundamentals", targetLevel: 3 },
      { skillId: "cryptography", targetLevel: 2 },
      { skillId: "web-security", targetLevel: 2 },
      { skillId: "threat-analysis", targetLevel: 3 },
      { skillId: "incident-response", targetLevel: 2 },
    ],
  },
];

export const ROLE_BY_ID: Record<string, Role> = Object.fromEntries(
  ROLES.map((r) => [r.id, r]),
);
