import type { Skill } from "@/lib/domain/types";

// ── Skill graph ───────────────────────────────────────────────────────────────
// `tier` is a rough foundational→advanced ordering; `prerequisites` form a DAG
// used for topological ordering and step-locking. Kept intentionally acyclic.
//
// Skills are keyed to CAPABILITIES, never to careers — one skill is reused by
// every goal that needs it. `aliases` let free-text goals resolve to a skill
// ("k8s", "black-scholes", "gdb"); `related` lets an under-specified goal
// expand sideways into the rest of its neighbourhood.

export const SKILLS: Skill[] = [
  // ── Programming / foundations ──────────────────────────────────────────────
  { id: "programming-fundamentals", name: "Programming Fundamentals", domain: "Programming", tier: 1, prerequisites: [], description: "Variables, control flow, functions, and data structures.", aliases: ["coding", "programming", "software basics", "learn to code", "code"], related: ["python", "algorithms", "git"] },
  { id: "python", name: "Python", domain: "Programming", tier: 1, prerequisites: [], description: "General-purpose programming with Python, the lingua franca of data & AI.", aliases: ["python3", "cpython"], related: ["data-wrangling", "testing", "programming-fundamentals"] },
  { id: "c-programming", name: "C Programming", domain: "Systems", tier: 2, prerequisites: ["programming-fundamentals"], description: "Manual memory, pointers, and the language systems are written in.", aliases: ["c", "c language", "ansi c", "c99"], related: ["memory-management", "debugging-tools", "systems-programming"] },
  { id: "cpp-programming", name: "C++", domain: "Systems", tier: 2, prerequisites: ["programming-fundamentals"], description: "Modern C++: RAII, templates, move semantics, and the STL.", aliases: ["c++", "cpp", "modern c++", "c plus plus"], related: ["performance-optimization", "computer-graphics", "algorithms"] },
  { id: "algorithms", name: "Algorithms & Data Structures", domain: "Computer Science", tier: 2, prerequisites: ["programming-fundamentals"], description: "Complexity analysis, trees, graphs, sorting, and search.", aliases: ["dsa", "data structures", "big o", "leetcode", "complexity"], related: ["discrete-math", "cpp-programming", "optimization"] },
  { id: "git", name: "Git & Version Control", domain: "Software", tier: 1, prerequisites: [], description: "Track changes, branch, and collaborate with Git.", aliases: ["github", "version control", "source control"], related: ["ci-cd", "testing"] },
  { id: "linux-cli", name: "Linux & Command Line", domain: "Software", tier: 1, prerequisites: [], description: "Navigate and operate systems from the shell.", aliases: ["linux", "bash", "shell", "unix", "terminal", "command line"], related: ["operating-systems", "docker", "systems-programming"] },

  // ── Math ──────────────────────────────────────────────────────────────────
  { id: "math-linear-algebra", name: "Linear Algebra", domain: "Math", tier: 2, prerequisites: [], description: "Vectors, matrices, and the operations underpinning ML, graphics, and control.", aliases: ["linear algebra", "matrices", "vectors", "eigenvalues", "maths", "mathematics"], related: ["calculus", "numerical-methods", "optimization"] },
  { id: "calculus", name: "Calculus", domain: "Math", tier: 2, prerequisites: [], description: "Derivatives, integrals, and multivariable calculus.", aliases: ["differential equations", "integrals", "multivariable calculus", "vector calculus"], related: ["math-linear-algebra", "optimization", "signal-processing"] },
  { id: "statistics", name: "Statistics", domain: "Math", tier: 2, prerequisites: [], description: "Descriptive and inferential statistics for data work.", aliases: ["stats", "hypothesis testing", "regression analysis"], related: ["probability", "time-series", "eda"] },
  { id: "probability", name: "Probability", domain: "Math", tier: 2, prerequisites: [], description: "Distributions, expectation, and probabilistic reasoning.", aliases: ["bayesian", "random variables", "stochastic"], related: ["statistics", "stochastic-processes", "state-estimation"] },
  { id: "discrete-math", name: "Discrete Mathematics", domain: "Math", tier: 2, prerequisites: [], description: "Logic, combinatorics, graph theory, and proof.", aliases: ["combinatorics", "graph theory", "logic", "set theory"], related: ["algorithms", "cryptography", "quantum-algorithms"] },
  { id: "optimization", name: "Optimization", domain: "Math", tier: 3, prerequisites: ["calculus", "math-linear-algebra"], description: "Convex optimization, gradients, constraints, and solvers.", aliases: ["convex optimization", "mathematical optimization", "linear programming", "gradient descent"], related: ["numerical-methods", "optimal-control", "portfolio-theory"] },
  { id: "numerical-methods", name: "Numerical Methods", domain: "Math", tier: 3, prerequisites: ["calculus", "math-linear-algebra"], description: "Floating-point error, solvers, integration, and stability.", aliases: ["numerical analysis", "scientific computing", "finite difference"], related: ["optimization", "physics-simulation", "signal-processing"] },
  { id: "stochastic-processes", name: "Stochastic Processes", domain: "Math", tier: 4, prerequisites: ["probability", "calculus"], description: "Markov chains, Brownian motion, and Itô calculus.", aliases: ["stochastic calculus", "brownian motion", "ito calculus", "markov chain", "random processes"], related: ["derivatives-pricing", "time-series", "probability"] },

  // ── Data ──────────────────────────────────────────────────────────────────
  { id: "sql", name: "SQL", domain: "Data", tier: 2, prerequisites: ["programming-fundamentals"], description: "Query and shape relational data.", aliases: ["postgres", "postgresql", "mysql", "queries", "joins"], related: ["databases", "data-engineering"] },
  { id: "data-wrangling", name: "Data Wrangling (NumPy/Pandas)", domain: "Data", tier: 2, prerequisites: ["python"], description: "Manipulate arrays and dataframes with NumPy and Pandas.", aliases: ["pandas", "numpy", "dataframe", "dataframes", "data manipulation"], related: ["data-cleaning", "eda", "data-visualization"] },
  { id: "data-visualization", name: "Data Visualization", domain: "Data", tier: 2, prerequisites: ["python", "statistics"], description: "Communicate insight with charts and dashboards.", aliases: ["matplotlib", "charts", "dashboards", "tableau", "plotting", "bi"], related: ["eda", "data-wrangling"] },
  { id: "data-cleaning", name: "Data Cleaning", domain: "Data", tier: 2, prerequisites: ["data-wrangling"], description: "Handle missing, dirty, and inconsistent data.", aliases: ["data quality", "preprocessing", "missing data"], related: ["data-wrangling", "feature-engineering"] },
  { id: "eda", name: "Exploratory Data Analysis", domain: "Data", tier: 3, prerequisites: ["data-wrangling", "statistics", "data-visualization"], description: "Profile datasets to form hypotheses.", aliases: ["eda", "exploratory analysis", "data analysis"], related: ["statistics", "data-visualization"] },
  { id: "data-engineering", name: "Data Engineering", domain: "Data", tier: 4, prerequisites: ["sql", "python"], description: "Build ETL/ELT pipelines and warehouse models.", aliases: ["etl", "elt", "data pipelines", "airflow", "dbt", "data warehouse"], related: ["big-data", "streaming-data", "databases"] },
  { id: "big-data", name: "Big Data Processing", domain: "Data", tier: 4, prerequisites: ["data-engineering"], description: "Distributed batch processing with Spark-style engines.", aliases: ["spark", "hadoop", "pyspark", "mapreduce", "distributed data"], related: ["streaming-data", "data-engineering"] },
  { id: "streaming-data", name: "Streaming Data", domain: "Data", tier: 5, prerequisites: ["data-engineering"], description: "Event streams, exactly-once semantics, and windowing.", aliases: ["kafka", "stream processing", "real time data", "flink", "event streaming"], related: ["big-data", "distributed-systems"] },

  // ── Machine Learning ──────────────────────────────────────────────────────
  { id: "ml-fundamentals", name: "ML Fundamentals", domain: "Machine Learning", tier: 3, prerequisites: ["data-wrangling", "statistics", "math-linear-algebra"], description: "Core ideas: training, generalization, bias/variance.", aliases: ["machine learning", "ml", "sklearn", "scikit-learn"], related: ["supervised-learning", "feature-engineering", "model-evaluation"] },
  { id: "supervised-learning", name: "Supervised Learning", domain: "Machine Learning", tier: 3, prerequisites: ["ml-fundamentals"], description: "Regression and classification models.", aliases: ["classification", "regression", "gradient boosting", "random forest", "xgboost"], related: ["model-evaluation", "feature-engineering"] },
  { id: "unsupervised-learning", name: "Unsupervised Learning", domain: "Machine Learning", tier: 3, prerequisites: ["ml-fundamentals"], description: "Clustering and dimensionality reduction.", aliases: ["clustering", "kmeans", "pca", "dimensionality reduction"], related: ["supervised-learning", "embeddings"] },
  { id: "model-evaluation", name: "Model Evaluation", domain: "Machine Learning", tier: 3, prerequisites: ["supervised-learning"], description: "Metrics, validation, and avoiding leakage.", aliases: ["cross validation", "metrics", "roc auc", "overfitting"], related: ["ml-fundamentals", "llm-evaluation"] },
  { id: "feature-engineering", name: "Feature Engineering", domain: "Machine Learning", tier: 3, prerequisites: ["data-wrangling", "ml-fundamentals"], description: "Transform raw data into predictive features.", aliases: ["features", "feature selection", "encoding"], related: ["data-cleaning", "supervised-learning"] },
  { id: "deep-learning", name: "Deep Learning", domain: "Machine Learning", tier: 4, prerequisites: ["supervised-learning", "math-linear-algebra"], description: "Neural networks with PyTorch/TensorFlow.", aliases: ["neural network", "neural networks", "pytorch", "tensorflow", "cnn", "transformer", "backpropagation"], related: ["computer-vision", "nlp", "reinforcement-learning"] },
  { id: "nlp", name: "Natural Language Processing", domain: "Machine Learning", tier: 4, prerequisites: ["deep-learning"], description: "Model and process human language.", aliases: ["nlp", "text mining", "tokenization", "language models"], related: ["llm-fundamentals", "embeddings"] },
  { id: "computer-vision", name: "Computer Vision", domain: "Machine Learning", tier: 4, prerequisites: ["deep-learning"], description: "Model and interpret images.", aliases: ["cv", "image processing", "opencv", "object detection", "vision"], related: ["slam", "signal-processing", "deep-learning"] },
  { id: "reinforcement-learning", name: "Reinforcement Learning", domain: "Machine Learning", tier: 5, prerequisites: ["deep-learning", "probability"], description: "Agents that learn from reward: policies, value functions, exploration.", aliases: ["rl", "deep rl", "q learning", "policy gradient", "reward"], related: ["optimal-control", "autonomous-systems", "agents"] },

  // ── MLOps / ML Engineering ────────────────────────────────────────────────
  { id: "software-apis", name: "REST APIs", domain: "Software", tier: 3, prerequisites: ["programming-fundamentals"], description: "Design and build HTTP APIs.", aliases: ["rest api", "apis", "api", "fastapi", "http", "backend", "web services"], related: ["databases", "system-design", "testing"] },
  { id: "model-deployment", name: "Model Deployment", domain: "MLOps", tier: 4, prerequisites: ["ml-fundamentals", "software-apis"], description: "Serve models behind an API.", aliases: ["model serving", "inference api", "deploy model"], related: ["mlops", "docker", "ml-pipelines"] },
  { id: "ml-pipelines", name: "ML Pipelines", domain: "MLOps", tier: 4, prerequisites: ["model-deployment", "data-wrangling"], description: "Automate training and data workflows.", aliases: ["training pipeline", "feature store", "kubeflow"], related: ["mlops", "data-engineering"] },
  { id: "mlops", name: "MLOps", domain: "MLOps", tier: 5, prerequisites: ["model-deployment", "docker"], description: "Operationalize ML: CI/CD, registries, reproducibility.", aliases: ["mlops", "ml engineering", "mlflow", "model registry", "experiment tracking"], related: ["model-monitoring", "ci-cd", "kubernetes"] },
  { id: "model-monitoring", name: "Model Monitoring", domain: "MLOps", tier: 5, prerequisites: ["mlops"], description: "Detect drift and degradation in production.", aliases: ["drift detection", "observability", "data drift"], related: ["mlops", "model-evaluation"] },

  // ── Software ──────────────────────────────────────────────────────────────
  { id: "databases", name: "Databases", domain: "Software", tier: 3, prerequisites: ["sql"], description: "Relational modeling, indexing, transactions.", aliases: ["rdbms", "indexes", "transactions", "acid", "nosql"], related: ["system-design", "data-engineering"] },
  { id: "testing", name: "Software Testing", domain: "Software", tier: 3, prerequisites: ["programming-fundamentals"], description: "Unit, integration, and automated testing.", aliases: ["unit tests", "pytest", "tdd", "test automation", "qa"], related: ["ci-cd", "debugging-tools"] },
  { id: "system-design", name: "System Design", domain: "Software", tier: 4, prerequisites: ["software-apis", "databases"], description: "Design scalable, reliable services.", aliases: ["architecture", "scalability", "caching", "load balancing", "microservices"], related: ["distributed-systems", "cloud-compute"] },
  { id: "distributed-systems", name: "Distributed Systems", domain: "Software", tier: 5, prerequisites: ["system-design", "networking"], description: "Consensus, replication, partitioning, and failure modes.", aliases: ["distributed computing", "consensus", "raft", "paxos", "cap theorem"], related: ["streaming-data", "kubernetes", "concurrency"] },
  { id: "web-frontend", name: "Web Frontend", domain: "Software", tier: 2, prerequisites: ["programming-fundamentals"], description: "HTML, CSS, JavaScript, and component-based UI.", aliases: ["frontend", "html", "css", "javascript", "react", "typescript", "web development", "ui"], related: ["software-apis", "web-security", "mobile-development"] },
  { id: "mobile-development", name: "Mobile Development", domain: "Software", tier: 3, prerequisites: ["programming-fundamentals"], description: "Build native or cross-platform mobile apps.", aliases: ["android", "ios", "flutter", "react native", "swift", "kotlin", "mobile app"], related: ["web-frontend", "software-apis"] },

  // ── Systems / low level ───────────────────────────────────────────────────
  { id: "computer-architecture", name: "Computer Architecture", domain: "Systems", tier: 2, prerequisites: [], description: "CPUs, caches, pipelines, and the memory hierarchy.", aliases: ["cpu architecture", "caches", "pipelining", "risc", "x86", "arm"], related: ["assembly", "performance-optimization", "operating-systems"] },
  { id: "assembly", name: "Assembly Language", domain: "Systems", tier: 3, prerequisites: ["computer-architecture"], description: "Registers, calling conventions, and reading disassembly.", aliases: ["asm", "x86 assembly", "arm assembly", "disassembly"], related: ["reverse-engineering", "compilers", "c-programming"] },
  { id: "operating-systems", name: "Operating Systems", domain: "Systems", tier: 3, prerequisites: ["c-programming", "computer-architecture"], description: "Processes, scheduling, virtual memory, and system calls.", aliases: ["os", "os internals", "processes", "scheduling", "syscalls", "kernel basics"], related: ["memory-management", "concurrency", "filesystems"] },
  { id: "memory-management", name: "Memory Management", domain: "Systems", tier: 3, prerequisites: ["c-programming", "operating-systems"], description: "Virtual memory, allocators, paging, and leak hunting.", aliases: ["virtual memory", "paging", "malloc", "heap", "pointers", "allocator"], related: ["performance-optimization", "kernel-development"] },
  { id: "concurrency", name: "Concurrency & Parallelism", domain: "Systems", tier: 4, prerequisites: ["operating-systems"], description: "Threads, locks, atomics, and lock-free patterns.", aliases: ["threads", "multithreading", "parallel programming", "mutex", "race condition", "async"], related: ["distributed-systems", "performance-optimization", "rtos"] },
  { id: "systems-programming", name: "Systems Programming", domain: "Systems", tier: 4, prerequisites: ["c-programming", "operating-systems"], description: "Write software against the kernel interface: syscalls, IPC, signals.", aliases: ["low level programming", "posix", "ipc", "system calls", "unix programming"], related: ["network-programming", "kernel-development", "filesystems"] },
  { id: "debugging-tools", name: "Debugging & Profiling Tools", domain: "Systems", tier: 3, prerequisites: ["c-programming"], description: "GDB, sanitizers, valgrind, strace, and perf.", aliases: ["gdb", "valgrind", "strace", "profiler", "debugging", "sanitizers"], related: ["performance-optimization", "testing"] },
  { id: "build-systems", name: "Build Systems & Toolchains", domain: "Systems", tier: 3, prerequisites: ["c-programming"], description: "Compilation units, linking, Make/CMake, cross-compiling.", aliases: ["make", "makefile", "cmake", "linker", "toolchain", "cross compile"], related: ["compilers", "embedded-c"] },
  { id: "filesystems", name: "Filesystems", domain: "Systems", tier: 4, prerequisites: ["operating-systems"], description: "Inodes, journaling, VFS, and block layers.", aliases: ["file system", "vfs", "ext4", "inode", "block device"], related: ["kernel-development", "systems-programming"] },
  { id: "network-programming", name: "Network Programming", domain: "Systems", tier: 4, prerequisites: ["c-programming", "networking"], description: "Sockets, epoll, protocol implementation.", aliases: ["sockets", "socket programming", "tcp programming", "epoll"], related: ["systems-programming", "distributed-systems"] },
  { id: "performance-optimization", name: "Performance Optimization", domain: "Systems", tier: 4, prerequisites: ["computer-architecture", "concurrency"], description: "Measure first: cache locality, branch prediction, hot paths.", aliases: ["profiling", "perf tuning", "cache optimization", "latency", "benchmarking", "optimisation"], related: ["low-latency-programming", "gpu-programming", "debugging-tools"] },
  { id: "kernel-development", name: "Kernel Development", domain: "Systems", tier: 5, prerequisites: ["operating-systems", "memory-management", "systems-programming"], description: "Build and modify kernel code: modules, locking, kernel APIs.", aliases: ["linux kernel", "kernel programming", "kernel hacking", "kernel module", "kernel internals"], related: ["device-drivers", "filesystems", "debugging-tools"] },
  { id: "device-drivers", name: "Device Drivers", domain: "Systems", tier: 5, prerequisites: ["kernel-development"], description: "Character/block drivers, interrupts, and DMA.", aliases: ["driver development", "char device", "device driver", "interrupts", "dma"], related: ["kernel-development", "hardware-interfaces"] },
  { id: "compilers", name: "Compilers", domain: "Systems", tier: 5, prerequisites: ["cpp-programming", "computer-architecture"], description: "Lexing, parsing, IR, and code generation.", aliases: ["compiler design", "llvm", "parsing", "lexer", "code generation", "interpreter"], related: ["assembly", "performance-optimization"] },

  // ── Embedded ──────────────────────────────────────────────────────────────
  { id: "digital-electronics", name: "Digital Electronics", domain: "Embedded", tier: 2, prerequisites: [], description: "Logic gates, timing, and reading a datasheet.", aliases: ["electronics", "circuits", "logic gates", "breadboard"], related: ["microcontrollers", "fpga-verilog", "hardware-interfaces"] },
  { id: "embedded-c", name: "Embedded C", domain: "Embedded", tier: 3, prerequisites: ["c-programming"], description: "Bare-metal C: registers, volatile, no heap, tight budgets.", aliases: ["embedded programming", "firmware", "bare metal", "embedded software"], related: ["microcontrollers", "rtos", "build-systems"] },
  { id: "microcontrollers", name: "Microcontrollers", domain: "Embedded", tier: 3, prerequisites: ["embedded-c"], description: "Program MCUs: clocks, timers, interrupts, and peripherals.", aliases: ["mcu", "arduino", "stm32", "esp32", "raspberry pi pico", "avr"], related: ["hardware-interfaces", "rtos", "digital-electronics"] },
  { id: "hardware-interfaces", name: "Hardware Interfaces", domain: "Embedded", tier: 3, prerequisites: ["microcontrollers"], description: "GPIO, I2C, SPI, UART, ADC, and PWM.", aliases: ["i2c", "spi", "uart", "gpio", "pwm", "adc", "serial"], related: ["sensors-actuators", "device-drivers"] },
  { id: "rtos", name: "Real-Time Operating Systems", domain: "Embedded", tier: 4, prerequisites: ["embedded-c", "concurrency"], description: "Tasks, priorities, deadlines, and determinism.", aliases: ["freertos", "real time operating system", "rtos scheduling", "zephyr", "deadline scheduling"], related: ["microcontrollers", "control-systems", "concurrency"] },
  { id: "signal-processing", name: "Signal Processing", domain: "Embedded", tier: 4, prerequisites: ["calculus", "probability"], description: "Sampling, Fourier transforms, and digital filters.", aliases: ["dsp", "fourier", "fft", "filters", "signals"], related: ["state-estimation", "computer-vision", "numerical-methods"] },
  { id: "fpga-verilog", name: "FPGA & HDL", domain: "Embedded", tier: 5, prerequisites: ["digital-electronics"], description: "Describe hardware in Verilog/VHDL and synthesize it.", aliases: ["fpga", "verilog", "vhdl", "hdl", "systemverilog", "hardware design"], related: ["digital-electronics", "computer-architecture"] },

  // ── Robotics ──────────────────────────────────────────────────────────────
  { id: "robotics-fundamentals", name: "Robotics Fundamentals", domain: "Robotics", tier: 2, prerequisites: [], description: "Robot anatomy, coordinate frames, and the sense-plan-act loop.", aliases: ["robotics", "robot", "robots", "mechatronics"], related: ["kinematics", "sensors-actuators", "ros"] },
  { id: "sensors-actuators", name: "Sensors & Actuators", domain: "Robotics", tier: 2, prerequisites: ["robotics-fundamentals"], description: "IMUs, LiDAR, encoders, motors, and their error models.", aliases: ["sensors", "imu", "lidar", "encoders", "actuators", "motors", "servo", "sonar"], related: ["state-estimation", "hardware-interfaces", "signal-processing"] },
  { id: "kinematics", name: "Kinematics & Dynamics", domain: "Robotics", tier: 3, prerequisites: ["math-linear-algebra", "robotics-fundamentals"], description: "Forward/inverse kinematics, Jacobians, and rigid-body dynamics.", aliases: ["forward kinematics", "inverse kinematics", "robot arm", "manipulator", "dynamics"], related: ["control-systems", "motion-planning", "physics-simulation"] },
  { id: "control-systems", name: "Control Systems", domain: "Robotics", tier: 3, prerequisites: ["calculus", "math-linear-algebra"], description: "Feedback, stability, PID, and state-space control.", aliases: ["control theory", "feedback control", "pid", "pid control", "state space", "controls", "control engineering"], related: ["optimal-control", "state-estimation", "rtos"] },
  { id: "robot-simulation", name: "Robot Simulation", domain: "Robotics", tier: 3, prerequisites: ["ros"], description: "Model robots and worlds in Gazebo/Isaac before touching hardware.", aliases: ["gazebo", "isaac sim", "simulation", "mujoco", "digital twin"], related: ["ros", "physics-simulation"] },
  { id: "ros", name: "ROS (Robot Operating System)", domain: "Robotics", tier: 3, prerequisites: ["robotics-fundamentals", "python", "linux-cli"], description: "Nodes, topics, services, and the ROS 2 toolchain.", aliases: ["ros2", "ros 2", "robot operating system", "rclpy", "rviz"], related: ["robot-simulation", "motion-planning", "sensors-actuators"] },
  { id: "state-estimation", name: "State Estimation", domain: "Robotics", tier: 4, prerequisites: ["probability", "math-linear-algebra"], description: "Kalman/particle filters and fusing noisy sensors.", aliases: ["kalman filter", "sensor fusion", "ekf", "particle filter", "localization", "localisation"], related: ["slam", "control-systems", "signal-processing"] },
  { id: "motion-planning", name: "Motion Planning", domain: "Robotics", tier: 4, prerequisites: ["robotics-fundamentals", "algorithms"], description: "Configuration space, RRT/PRM, and trajectory generation.", aliases: ["path planning", "rrt", "trajectory planning", "navigation", "planning"], related: ["autonomous-systems", "optimal-control", "kinematics"] },
  { id: "optimal-control", name: "Optimal Control", domain: "Robotics", tier: 5, prerequisites: ["control-systems", "numerical-methods"], description: "LQR, MPC, and control as constrained optimization.", aliases: ["mpc", "model predictive control", "lqr", "optimal control"], related: ["optimization", "reinforcement-learning", "motion-planning"] },
  { id: "slam", name: "SLAM", domain: "Robotics", tier: 5, prerequisites: ["state-estimation", "computer-vision"], description: "Simultaneous localization and mapping, loop closure, pose graphs.", aliases: ["slam", "simultaneous localization and mapping", "mapping", "visual odometry"], related: ["state-estimation", "autonomous-systems"] },
  { id: "autonomous-systems", name: "Autonomous Systems", domain: "Robotics", tier: 5, prerequisites: ["motion-planning", "state-estimation"], description: "Full autonomy stacks: perception → planning → control, and safety.", aliases: ["autonomy", "self driving", "autonomous navigation", "autonomous vehicles", "auv", "uav", "drone", "underwater robotics"], related: ["slam", "optimal-control", "reinforcement-learning"] },

  // ── Graphics / games ──────────────────────────────────────────────────────
  { id: "computer-graphics", name: "Computer Graphics", domain: "Graphics", tier: 3, prerequisites: ["math-linear-algebra", "cpp-programming"], description: "Transforms, cameras, lighting, and the graphics math stack.", aliases: ["graphics programming", "3d graphics", "graphics", "cg"], related: ["rendering-pipeline", "graphics-apis", "shaders"] },
  { id: "game-programming", name: "Game Programming", domain: "Graphics", tier: 3, prerequisites: ["cpp-programming"], description: "Game loops, entity systems, input, and gameplay code.", aliases: ["game development", "gamedev", "unity", "unreal", "godot", "games"], related: ["game-engine-architecture", "physics-simulation", "animation-systems"] },
  { id: "graphics-apis", name: "Graphics APIs", domain: "Graphics", tier: 4, prerequisites: ["computer-graphics"], description: "Drive the GPU with OpenGL/Vulkan/DirectX.", aliases: ["opengl", "vulkan", "directx", "metal", "webgl", "wgpu"], related: ["shaders", "rendering-pipeline", "gpu-programming"] },
  { id: "rendering-pipeline", name: "Rendering Pipeline", domain: "Graphics", tier: 4, prerequisites: ["computer-graphics"], description: "Rasterization, depth, culling, deferred/forward rendering.", aliases: ["rasterization", "render pipeline", "rendering", "renderer"], related: ["ray-tracing", "graphics-apis", "game-engine-architecture"] },
  { id: "shaders", name: "Shader Programming", domain: "Graphics", tier: 4, prerequisites: ["graphics-apis"], description: "Vertex/fragment/compute shaders in GLSL/HLSL.", aliases: ["glsl", "hlsl", "shader", "shader programming", "compute shader"], related: ["rendering-pipeline", "gpu-programming"] },
  { id: "physics-simulation", name: "Physics Simulation", domain: "Graphics", tier: 4, prerequisites: ["calculus", "cpp-programming"], description: "Integrators, rigid bodies, collision detection and response.", aliases: ["physics engine", "rigid body", "collision detection", "simulation physics", "cloth simulation"], related: ["numerical-methods", "game-engine-architecture", "robot-simulation"] },
  { id: "animation-systems", name: "Animation Systems", domain: "Graphics", tier: 4, prerequisites: ["computer-graphics"], description: "Skeletal animation, blending, skinning, and IK.", aliases: ["skeletal animation", "rigging", "animation", "skinning"], related: ["game-engine-architecture", "kinematics"] },
  { id: "ray-tracing", name: "Ray Tracing", domain: "Graphics", tier: 5, prerequisites: ["rendering-pipeline"], description: "Ray/path tracing, BVH acceleration, and global illumination.", aliases: ["raytracing", "path tracing", "global illumination", "ray tracer"], related: ["rendering-pipeline", "gpu-programming"] },
  { id: "gpu-programming", name: "GPU Programming", domain: "Graphics", tier: 5, prerequisites: ["cpp-programming", "computer-architecture"], description: "Massively parallel compute with CUDA-style kernels.", aliases: ["cuda", "gpgpu", "gpu compute", "opencl", "parallel gpu", "kernels"], related: ["performance-optimization", "shaders", "deep-learning"] },
  { id: "game-engine-architecture", name: "Game Engine Architecture", domain: "Graphics", tier: 5, prerequisites: ["rendering-pipeline", "cpp-programming", "performance-optimization"], description: "Subsystems, memory budgets, asset pipelines, and frame budgets.", aliases: ["game engine", "engine programming", "engine architecture", "ecs"], related: ["game-programming", "physics-simulation", "animation-systems"] },

  // ── Quantitative finance ──────────────────────────────────────────────────
  { id: "financial-markets", name: "Financial Markets", domain: "Quantitative Finance", tier: 2, prerequisites: [], description: "Instruments, venues, order books, and market mechanics.", aliases: ["markets", "trading", "equities", "finance", "order book", "market microstructure", "fixed income"], related: ["portfolio-theory", "quantitative-trading", "derivatives-pricing"] },
  { id: "time-series", name: "Time Series Analysis", domain: "Quantitative Finance", tier: 4, prerequisites: ["statistics", "probability"], description: "Stationarity, ARIMA/GARCH, and forecasting.", aliases: ["time series", "arima", "garch", "forecasting", "autocorrelation"], related: ["stochastic-processes", "quantitative-trading", "statistics"] },
  { id: "backtesting", name: "Backtesting", domain: "Quantitative Finance", tier: 4, prerequisites: ["python", "time-series"], description: "Simulate strategies honestly: costs, slippage, look-ahead bias.", aliases: ["backtest", "strategy testing", "walk forward", "vectorbt"], related: ["quantitative-trading", "portfolio-theory"] },
  { id: "portfolio-theory", name: "Portfolio Theory & Risk", domain: "Quantitative Finance", tier: 4, prerequisites: ["statistics", "financial-markets", "optimization"], description: "Mean-variance, factor models, VaR, and risk budgeting.", aliases: ["portfolio optimization", "risk management", "markowitz", "var", "factor models", "sharpe"], related: ["optimization", "quantitative-trading"] },
  { id: "derivatives-pricing", name: "Derivatives Pricing", domain: "Quantitative Finance", tier: 5, prerequisites: ["stochastic-processes", "financial-markets"], description: "Black-Scholes, Greeks, Monte Carlo, and PDE methods.", aliases: ["options pricing", "black scholes", "black-scholes", "derivatives", "greeks", "monte carlo pricing", "quantitative finance"], related: ["stochastic-processes", "numerical-methods"] },
  { id: "quantitative-trading", name: "Quantitative Trading", domain: "Quantitative Finance", tier: 5, prerequisites: ["time-series", "financial-markets", "backtesting"], description: "Signal research, execution, and portfolio construction end to end.", aliases: ["algo trading", "algorithmic trading", "systematic trading", "quant trading", "quant", "alpha research", "trading strategies"], related: ["portfolio-theory", "low-latency-programming", "backtesting"] },
  { id: "low-latency-programming", name: "Low-Latency Programming", domain: "Quantitative Finance", tier: 5, prerequisites: ["cpp-programming", "performance-optimization"], description: "Nanosecond budgets: cache lines, lock-free queues, kernel bypass.", aliases: ["hft", "high frequency trading", "low latency", "ultra low latency"], related: ["performance-optimization", "network-programming", "concurrency"] },

  // ── Quantum computing ─────────────────────────────────────────────────────
  { id: "quantum-mechanics", name: "Quantum Mechanics", domain: "Quantum Computing", tier: 3, prerequisites: ["math-linear-algebra", "calculus"], description: "States, superposition, measurement, and Dirac notation.", aliases: ["quantum physics", "qm", "superposition", "wave function"], related: ["quantum-computing", "quantum-algorithms"] },
  { id: "quantum-computing", name: "Quantum Computing", domain: "Quantum Computing", tier: 4, prerequisites: ["quantum-mechanics", "math-linear-algebra"], description: "Qubits, gates, circuits, and entanglement.", aliases: ["qubits", "quantum computer", "quantum gates", "quantum circuits", "quantum"], related: ["quantum-programming", "quantum-algorithms"] },
  { id: "quantum-programming", name: "Quantum Programming", domain: "Quantum Computing", tier: 4, prerequisites: ["quantum-computing", "python"], description: "Build and run circuits with Qiskit/Cirq on simulators and hardware.", aliases: ["qiskit", "cirq", "pennylane", "quantum sdk", "quantum software"], related: ["quantum-algorithms", "quantum-computing"] },
  { id: "quantum-algorithms", name: "Quantum Algorithms", domain: "Quantum Computing", tier: 5, prerequisites: ["quantum-computing", "discrete-math"], description: "Deutsch-Jozsa, Grover, Shor, VQE, and speedup analysis.", aliases: ["grover", "shor", "quantum algorithm", "vqe", "qaoa"], related: ["quantum-error-correction", "quantum-programming"] },
  { id: "quantum-error-correction", name: "Quantum Error Correction", domain: "Quantum Computing", tier: 5, prerequisites: ["quantum-algorithms"], description: "Noise, stabilizer codes, surface codes, and fault tolerance.", aliases: ["error correction", "surface code", "stabilizer codes", "fault tolerance"], related: ["quantum-algorithms", "quantum-computing"] },

  // ── Cloud / DevOps ────────────────────────────────────────────────────────
  { id: "docker", name: "Docker & Containers", domain: "Cloud", tier: 3, prerequisites: ["linux-cli"], description: "Package apps into portable containers.", aliases: ["docker", "containers", "containerization", "dockerfile", "podman"], related: ["kubernetes", "ci-cd", "cloud-compute"] },
  { id: "ci-cd", name: "CI/CD", domain: "Cloud", tier: 4, prerequisites: ["git", "docker", "testing"], description: "Automate build, test, and release.", aliases: ["continuous integration", "github actions", "jenkins", "pipelines", "devops"], related: ["infrastructure-as-code", "mlops"] },
  { id: "cloud-fundamentals", name: "Cloud Fundamentals", domain: "Cloud", tier: 3, prerequisites: ["linux-cli"], description: "Core cloud concepts and the shared-responsibility model.", aliases: ["aws", "azure", "gcp", "cloud", "cloud computing"], related: ["cloud-compute", "cloud-storage", "cloud-security"] },
  { id: "cloud-compute", name: "Cloud Compute", domain: "Cloud", tier: 3, prerequisites: ["cloud-fundamentals"], description: "VMs, serverless, and autoscaling.", aliases: ["ec2", "serverless", "lambda", "autoscaling", "vms"], related: ["kubernetes", "system-design"] },
  { id: "cloud-storage", name: "Cloud Storage & Databases", domain: "Cloud", tier: 3, prerequisites: ["cloud-fundamentals"], description: "Object stores, managed databases, and caching.", aliases: ["s3", "object storage", "managed database", "redis", "blob storage"], related: ["databases", "data-engineering"] },
  { id: "infrastructure-as-code", name: "Infrastructure as Code", domain: "Cloud", tier: 4, prerequisites: ["cloud-fundamentals"], description: "Provision infra declaratively (Terraform).", aliases: ["terraform", "iac", "ansible", "cloudformation", "pulumi"], related: ["ci-cd", "kubernetes"] },
  { id: "kubernetes", name: "Kubernetes", domain: "Cloud", tier: 5, prerequisites: ["docker", "cloud-compute"], description: "Orchestrate containers at scale.", aliases: ["k8s", "kubernetes", "helm", "orchestration", "eks", "gke"], related: ["distributed-systems", "mlops", "infrastructure-as-code"] },

  // ── AI & LLMs ─────────────────────────────────────────────────────────────
  { id: "llm-fundamentals", name: "LLM Fundamentals", domain: "AI & LLMs", tier: 3, prerequisites: ["python"], description: "How large language models work: tokens, context, sampling.", aliases: ["llm", "llms", "large language models", "gpt", "generative ai", "genai"], related: ["prompt-engineering", "embeddings", "nlp"] },
  { id: "prompt-engineering", name: "Prompt Engineering", domain: "AI & LLMs", tier: 3, prerequisites: ["llm-fundamentals"], description: "Design reliable prompts and structured outputs.", aliases: ["prompt", "prompting", "prompt design", "few shot"], related: ["llm-apps", "llm-evaluation"] },
  { id: "embeddings", name: "Embeddings", domain: "AI & LLMs", tier: 3, prerequisites: ["llm-fundamentals"], description: "Represent meaning as vectors for search & retrieval.", aliases: ["embeddings", "vector search", "semantic search", "cosine similarity"], related: ["vector-databases", "rag", "unsupervised-learning"] },
  { id: "vector-databases", name: "Vector Databases", domain: "AI & LLMs", tier: 4, prerequisites: ["embeddings"], description: "Store and query embeddings at scale.", aliases: ["pinecone", "weaviate", "qdrant", "faiss", "vector store", "pgvector"], related: ["rag", "embeddings"] },
  { id: "rag", name: "Retrieval-Augmented Generation", domain: "AI & LLMs", tier: 4, prerequisites: ["prompt-engineering", "embeddings"], description: "Ground LLM answers in your own data.", aliases: ["rag", "retrieval augmented generation", "chunking", "reranking"], related: ["vector-databases", "agents", "llm-apps"] },
  { id: "llm-apps", name: "Building LLM Applications", domain: "AI & LLMs", tier: 4, prerequisites: ["prompt-engineering", "software-apis"], description: "Ship production apps on top of LLM APIs.", aliases: ["ai engineer", "ai engineering", "llm app", "langchain", "chatbot", "ai application"], related: ["rag", "agents", "llm-evaluation"] },
  { id: "llm-evaluation", name: "LLM Evaluation", domain: "AI & LLMs", tier: 4, prerequisites: ["llm-apps"], description: "Measure quality, safety, and regressions.", aliases: ["evals", "llm eval", "guardrails", "hallucination"], related: ["model-evaluation", "llm-apps"] },
  { id: "agents", name: "AI Agents", domain: "AI & LLMs", tier: 5, prerequisites: ["llm-apps", "rag"], description: "Tool-using, multi-step autonomous systems.", aliases: ["ai agents", "agentic", "tool use", "function calling", "mcp"], related: ["llm-apps", "reinforcement-learning"] },
  { id: "fine-tuning", name: "Fine-Tuning", domain: "AI & LLMs", tier: 5, prerequisites: ["deep-learning", "llm-fundamentals"], description: "Adapt models to a domain or task.", aliases: ["fine tuning", "lora", "peft", "sft", "rlhf", "training llms"], related: ["deep-learning", "llm-evaluation"] },

  // ── Security ──────────────────────────────────────────────────────────────
  { id: "security-fundamentals", name: "Security Fundamentals", domain: "Security", tier: 2, prerequisites: [], description: "CIA triad, threats, and defense in depth.", aliases: ["security", "cybersecurity", "infosec", "cyber security", "information security"], related: ["networking", "cryptography", "threat-analysis"] },
  { id: "networking", name: "Networking", domain: "Security", tier: 2, prerequisites: [], description: "TCP/IP, DNS, and the protocols attacks ride on.", aliases: ["tcp/ip", "dns", "networks", "computer networks", "routing", "http protocol"], related: ["network-programming", "web-security", "distributed-systems"] },
  { id: "cryptography", name: "Cryptography", domain: "Security", tier: 3, prerequisites: ["security-fundamentals"], description: "Hashing, symmetric/asymmetric encryption, TLS.", aliases: ["crypto", "encryption", "tls", "hashing", "pki", "aes", "rsa"], related: ["security-fundamentals", "quantum-algorithms", "discrete-math"] },
  { id: "web-security", name: "Web Security", domain: "Security", tier: 3, prerequisites: ["security-fundamentals", "software-apis"], description: "OWASP Top 10 and secure web apps.", aliases: ["owasp", "xss", "sql injection", "csrf", "appsec", "application security"], related: ["pen-testing", "web-frontend"] },
  { id: "threat-analysis", name: "Threat Analysis", domain: "Security", tier: 4, prerequisites: ["security-fundamentals", "networking"], description: "Identify, model, and prioritize threats.", aliases: ["threat modeling", "threat intelligence", "risk assessment", "blue team", "soc"], related: ["incident-response", "cloud-security"] },
  { id: "incident-response", name: "Incident Response", domain: "Security", tier: 4, prerequisites: ["threat-analysis"], description: "Detect, contain, and recover from incidents.", aliases: ["dfir", "forensics", "siem", "incident handling"], related: ["threat-analysis", "reverse-engineering"] },
  { id: "cloud-security", name: "Cloud Security", domain: "Security", tier: 4, prerequisites: ["cloud-fundamentals", "security-fundamentals"], description: "Identity, least privilege, network boundaries, and posture.", aliases: ["iam", "cspm", "zero trust", "devsecops", "secure cloud"], related: ["threat-analysis", "infrastructure-as-code"] },
  { id: "pen-testing", name: "Penetration Testing", domain: "Security", tier: 4, prerequisites: ["web-security", "networking"], description: "Authorized offensive testing of systems.", aliases: ["pentest", "penetration testing", "ethical hacking", "red team", "offensive security", "ctf"], related: ["binary-exploitation", "reverse-engineering", "web-security"] },
  { id: "reverse-engineering", name: "Reverse Engineering", domain: "Security", tier: 5, prerequisites: ["assembly", "c-programming"], description: "Static and dynamic analysis of compiled binaries.", aliases: ["binary analysis", "malware analysis", "ghidra", "ida", "decompilation"], related: ["binary-exploitation", "assembly", "incident-response"] },
  { id: "binary-exploitation", name: "Binary Exploitation", domain: "Security", tier: 5, prerequisites: ["reverse-engineering", "memory-management"], description: "Memory-safety bugs and mitigations, in authorized lab/CTF settings.", aliases: ["pwn", "buffer overflow", "rop", "exploit development", "memory corruption"], related: ["reverse-engineering", "pen-testing"] },
];

export const SKILL_BY_ID: Record<string, Skill> = Object.fromEntries(
  SKILLS.map((s) => [s.id, s]),
);
